seq_len: 256
vocab_size: 4000
n_layers: 4
n_heads: 4
d_model: 256
d_ff: 1024
dropout: 0.1
batch_size: 8
lr: 2.5e-4
min_lr: 1.0e-5
warmup_steps: 200
max_steps: 2000
weight_decay: 0.01
grad_accum_steps: 2
compile: false
